### ISSUE TITLE
config.json在哪里？

### ISSUE THREAD

**Issue by cuidingfeng** [fex-team/yog-log#6]
用yog2创建的项目，没有找到哪里有config.json啊，怎么开启yog-log呢？

在代码中require('yog-log')，提示cannot find module 'yog-log'

yog-log不是内置的吗？还需要单独安装吗？

**Comment by hefangshi** [comment]
不需要单独安装，不需要自行require，如果你跟着文档走，直接使用

```
yog.log.notice('xxx');
yog.log.fatal('xxx');
```

即可
